#!/bin/bash

# Applying prod config before building
./setup-config prod

# Fetching build number
version=$(grep 'fulgurogo.version.name' gradle.properties | sed 's/fulgurogo.version.name=\(.*\)/\1/')

./gradlew clean :app:shadowJar

mv app/build/libs/app-${version}-all.jar export/fulgurobot-${version}.jar

# Rolling back to git config
./setup-config git
