rootProject.name = providers.gradleProperty("fulgurogo.project.name").get()
include("app")
include("common")
include("discord")
include("kgs")
include("ogs")
include("fox")
include("igs")
include("ffg")
include("egf")
include("gold")
