rootProject.name = providers.gradleProperty("fulgurogo.project.name").get()
include("app")
include(":modules:common")
include(":modules:discord")
include(":modules:kgs")
include(":modules:ogs")
include(":modules:fox")
include(":modules:igs")
include(":modules:ffg")
include(":modules:egf")

include(":modules:gold")
include(":modules:fgc")

include(":modules:ping")
include(":modules:clean")
