#!/bin/sh

# Exit script at first error:
set -e

function printHelp() {
  echo ""
  echo "USAGE: setup-config <env>"
  echo "    dev         Sets up app for dev environment"
  echo "    prod        Sets up app for prod environment"
  echo "    git         Sets up app for git commit (hiding app keys)"
}

function setup() {
  cp ${file} app/src/main/kotlin/com/fulgurogo/Config.kt
}

if [ -f "./gradlew" ]; then
  case $1 in
  "dev")
    file="assets/DevConfig.kt"
    setup
    exit 0
    ;;
  "prod")
    file="assets/ProdConfig.kt"
    setup
    ;;
  "git")
    file="assets/GitConfig.kt"
    setup
    ;;
  *)
    echo "Unknown argument"
    printHelp
    exit 0
    ;;
  esac
else
  echo "This script should be run at the root of the repo."
  exit 1
fi
